services:
  chroma:
    container_name: chroma
    image: chromadb/chroma
    volumes:
      - ./chroma_data:/chroma/chroma
    ports:
      - "8000:8000"

  server:
    container_name: server
    image: cameronnimmo/ml-search
    env_file: .env
    environment:
      CHROMA_HOST: chroma
      CHROMA_PORT: 8000
    ports:
      - "80:8080"
