services:
  fastapi:
    container_name: fastapi
    image: cameronnimmo/recipise-fastapi
    platform: linux/amd64
    env_file: .env
    volumes:
      - ./decoder-weights.pt:/code/decoder-weights.pt

  next:
    container_name: next
    image: cameronnimmo/recipise-next
    platform: linux/amd64
    env_file: .env
    environment:
      SERVER_URL: http://fastapi:8080
    ports:
      - "80:3000"
    depends_on: 
      - fastapi
